# config/packages/api_platform.yaml
api_platform:
  enable_docs: true
  show_webby: false
  mapping:
    paths: ['%kernel.project_dir%/app/config/Resources/']
  patch_formats:
    json: ['application/merge-patch+json']
  swagger:
    versions: [3]
