kind: pipeline
type: docker
name: default
steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./vendor
    volumes:
      - name: cache
        path: /cache

  - name: build
    image: registry.gitlab.com/fun-tech/fundraising-frontend-docker:ci
    environment:
      COMPOSER_CACHE_DIR: /composer_cache
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: cache
        path: /composer_cache
    commands:
      # Environment setup
      - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
      - composer config -g github-oauth.github.com "$GITHUB_TOKEN"
      - composer install --prefer-dist --no-progress --no-interaction
      # CI
      - vendor/bin/phpcs
      - php -d xdebug.mode=coverage vendor/bin/phpunit --coverage-clover coverage.xml
      - php -d memory_limit=1G vendor/bin/phpstan analyse --level=5 --no-progress src/ tests/
      # Upload coverage to Scrutinizer
      - ocular code-coverage:upload --no-interaction --format=php-clover coverage.xml

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./vendor
    volumes:
      - name: cache
        path: /cache

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache
