#!/usr/bin/env php
<?php

use WMDE\Fundraising\Frontend\Cli\FundraisingCli;

require_once __DIR__ . '/vendor/autoload.php';

$dotenv = Dotenv\Dotenv::create(__DIR__);
$dotenv->load();

( new FundraisingCli() )->run();


