export const SET_BANKDATA = 'SET_BANKDATA';
export const SET_BANKNAME = 'SET_BANKNAME';
export const SET_BANK_DATA_VALIDITY = 'SET_BANK_DATA_VALIDITY';
export const MARK_EMPTY_FIELDS_INVALID = 'MARK_EMPTY_FIELDS_INVALID';
export const MARK_BANKDATA_INCOMPLETE = 'MARK_BANKDATA_INCOMPLETE';
