export const VALIDATE_INPUT: string = 'VALIDATE_INPUT';
export const MARK_EMPTY_FIELD_INVALID: string = 'MARK_EMPTY_FIELD_INVALID';
export const BEGIN_ADDRESS_VALIDATION: string = 'BEGIN_ADDRESS_VALIDATION';
export const FINISH_ADDRESS_VALIDATION: string = 'FINISH_ADDRESS_VALIDATION';
export const SET_ADDRESS_TYPE: string = 'SET_ADDRESS_TYPE';
