export const MARK_EMPTY_FIELD_INVALID = 'MARK_EMPTY_FIELD_INVALID';
export const SET_AMOUNT = 'SET_AMOUNT';
export const SET_AMOUNT_VALIDITY = 'SET_AMOUNT_VALIDITY';
export const SET_INTERVAL = 'SET_INTERVAL';
export const SET_OPTION = 'SET_OPTION';
