export const MARK_EMPTY_FIELD_INVALID = 'MARK_EMPTY_FIELD_INVALID';
export const REGISTER_AMOUNT = 'REGISTER_AMOUNT';
export const SET_AMOUNT_VALIDITY = 'SET_AMOUNT_VALIDITY';
export const REGISTER_INTERVAL = 'REGISTER_INTERVAL';
export const REGISTER_OPTION = 'REGISTER_OPTION';