export const MARK_EMPTY_AMOUNT_SELECTION_INVALID = 'MARK_EMPTY_AMOUNT_SELECTION_INVALID';
export const MARK_EMPTY_OPTION_SELECTION_INVALID = 'MARK_EMPTY_OPTION_SELECTION_INVALID';
export const SET_AMOUNT = 'SET_AMOUNT';
export const SET_AMOUNT_VALIDITY = 'SET_AMOUNT_VALIDITY';
export const SET_INTERVAL = 'SET_INTERVAL';
export const SET_OPTION = 'SET_OPTION';
