# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "trusty-cloud"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    # Needed mostly on Mac OS X: Always go through the system resolver, allowing us to redirect local domains.
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.define :test, primary: true do |test|
      test.vm.network "private_network", ip: "192.168.33.17"
  end

  config.vm.define :stage do |stage|
      stage.vm.network "private_network", ip: "192.168.33.18"
  end

  config.vm.define :production do |prod|
      prod.vm.network "private_network", ip: "192.168.33.19"
  end
end
