clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      # "partial: false" and depth will copy several commits from the source repo,
      # enabling history checks for the ocular tool
      # "lfs: false" disables downloading resources from LFS, which we don't use
      partial: false
      depth: 10
      lfs: false

steps:
  - name: build
    when:
      -   event: [ push, pull_request, cron, manual ]
    image: registry.gitlab.com/fun-tech/fundraising-frontend-docker:latest
    environment:
      COMPOSER_CACHE_DIR: /composer_cache
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - /tmp/woodpeckerci/cache:/composer_cache
    commands:
      # Environment setup
      - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
      - composer config -g github-oauth.github.com "$GITHUB_TOKEN"
      - composer install --prefer-dist --no-progress --no-interaction
      - echo "APP_ENV=dev" > .env
      - make default-config
      # CI
      - vendor/bin/phpcs
      - php -d xdebug.mode=coverage vendor/bin/phpunit --coverage-clover coverage.xml
      - php -d memory_limit=1G vendor/bin/phpstan analyse --level=9 --no-progress src/ tests/
      - php bin/console lint:container
      - php bin/console app:validate:config app/config/config.dist.json app/config/config.test.json
      - php bin/console app:validate:config app/config/config.dist.json .docker/app/config.dev.json
      - php bin/console app:validate:campaigns dev

  - name: upload-coverage
    image: registry.gitlab.com/fun-tech/fundraising-frontend-docker:ci
    environment:
    commands:
      # Upload coverage to Scrutinizer
      - ocular code-coverage:upload --no-interaction --format=php-clover coverage.xml
    when:
      event:
        - push
        - pull_request
